[algokit]
min_version = "v2.0.0"

[generate.import_contract]
description = "Import a typed client from your smart contracts project"
path = ".algokit/generators/import_contract"

[project]
type = "frontend"
name = 'production_beaker_react-frontend'
artifacts = "src/contracts"

[project.run]
build = { commands = ['npm run build'], description = 'Build frontend' }
test = { commands = ['npm run test'], description = 'Run frontend tests' }
lint = { commands = ['npm run lint'], description = 'Lint frontend code' }
ci-deploy-netlify = { commands = [
    'npm install --global netlify-cli@latest',
    'netlify login',
    'netlify deploy --build --prod'
  ], description = 'Deploy to Netlify' }
