[algokit]
min_version = "v1.12.1"

[project]
type = 'contract'
name = 'starter_tealscript_react-contracts'
artifacts = 'contracts/artifacts'

[project.run]
build = { commands = [ 
  'npm run build',
], description = 'Build all smart contracts in the project' }
test = { commands = [
  'npm run test',
], description = 'Run smart contract tests' }
