# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.0-20-gfaa6d61
_src_path: gh:algorandfoundation/algokit-puya-template
author_email: None
author_name: None
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: production_beaker_react-contracts

