# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.4-21-gdd86cf4
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: None
author_name: None
preset_name: starter
project_name: starter_puya_react-app

