[algokit]
min_version = "v2.0.0"

[project]
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = ['production_tealscript_react-contracts', 'production_tealscript_react-frontend']
