# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: <commit>
_src_path: <src>
author_email: None
author_name: None
cloud_provider: netlify
contract_name: Calculator
preset_name: production
project_name: production_tealscript_react

