# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: <commit>
_src_path: <src>
author_email: None
author_name: None
contract_name: hello_world
deployment_language: typescript
ide_vscode: true
preset_name: starter
project_name: test_all_default_parameters_off_starter
use_python_black: false
use_typescript_jest: false

