# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.1-5-g0c505db
_src_path: gh:algorandfoundation/algokit-puya-template
author_email: None
author_name: None
contract_name: hello_world
deployment_language: python
preset_name: production
project_name: production_puya_react-contracts

