# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: <commit>
_src_path: <src>
author_email: None
author_name: None
cloud_provider: netlify
contract_name: hello_world
deployment_language: python
ide_vscode: true
preset_name: production
project_name: test_all_default_parameters_on_production
python_linter: ruff
use_dispenser: true
use_github_actions: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

