# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.6
_src_path: gh:algorandfoundation/algokit-beaker-default-template
author_email: None
author_name: None
contract_name: hello_world
deployment_language: typescript
preset_name: starter
project_name: starter_beaker_react-contracts

