# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.4-19-gb77a62c
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: None
author_name: None
preset_name: production
project_name: production_beaker_react-app

