# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.1
_src_path: gh:algorandfoundation/algokit-typescript-template
author_email: None
author_name: None
contract_name: hello_world
preset_name: starter
project_name: s-ts-contracts

