# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.12.0
_src_path: gh:algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: None
author_name: None
contract_name: hello_world
deployment_language: typescript
ide_jetbrains: true
ide_vscode: false
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: starter
project_name: backend
use_python_black: false
use_typescript_jest: false

