# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.9.4-17-gd603f12
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: None
author_name: None
preset_name: production
project_name: production_tealscript_react-app

