# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.10.1-12-g317844b
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: None
author_name: None
preset_name: starter
project_name: starter_beaker_react-frontend

