name: Pull Request validation

on: [pull_request]


jobs:
  p-py-contracts-ci:
    name: Run p-py-contracts validation
    uses: ./.github/workflows/p-py-contracts-ci.yaml

  p-py-frontend-ci:
    name: Run p-py-frontend validation
    uses: ./.github/workflows/p-py-frontend-ci.yaml

