# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.7.1-9-ge1a1d57
_src_path: https://github.com/algorandfoundation/algokit-react-frontend-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: None
author_name: None
cloud_provider: netlify
ide_vscode: false
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
project_name: frontend
use_daisy_ui: true
use_eslint_prettier: false
use_github_actions: false
use_jest: false
use_playwright: false
use_tailwind: false

