name: Frontend CI

on:
  workflow_call:
    inputs:
      run-build:
        required: false
        type: boolean
        default: false

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install algokit
        run: pipx install algokit

      - name: Install dependencies
        working-directory: ./projects/production_beaker_react-app
        run: npm ci

      - name: Run linters
        working-directory: ./projects/production_beaker_react-app
        run: npm run lint

      - name: Run unit tests
        working-directory: ./projects/production_beaker_react-app
        run: npm run test

      - name: Create placeholder .env file
        if: ${{ inputs.run-build }}
        uses: makerxstudio/shared-config/.github/actions/env-to-placeholders@main
        with:
          env-output-path: ./projects/production_beaker_react-app/.env
          env-template-path: ./projects/production_beaker_react-app/.env.template
          env-variable-prefix: VITE_

      - name: Build
        if: ${{ inputs.run-build }}
        working-directory: ./projects/production_beaker_react-app
        run: npm run build

      - name: Archive
        if: ${{ inputs.run-build }}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: frontend/dist/
